version: '3'
services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: maquette
      MINIO_SECRET_KEY: password
    ports:
      - "9000:9000"
    volumes:
      - "minio_data:/data"
    command: "server /data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/data"
  
  pgadmin:
    image: dpage/pgadmin4:4.25
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: maquette@kpmg.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80

volumes:
  minio_data:
  postgres_data: