version: '3.3'

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    expose:
      - "80"
    ports:
      - "9080:80"
    networks:
      - backend
      - frontend
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@maquette.ai
      PGADMIN_DEFAULT_PASSWORD: password

  postgres:
    restart: always
    image: postgres:12.4
    container_name: postgres
    expose:
      - "5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data"

  minio:
    restart: always
    image: minio/minio:RELEASE.2020-12-12T08-39-07Z
    container_name: minio
    expose: 
      - "9000"
    networks:
      - backend
      - frontend
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "access"
      MINIO_SECRET_KEY: "secret1234"
      MINIO_REGION_NAME: "mzg"
    command: "server /data"

  mlflow:
    restart: always
    image: mq-stacks--mlflow
    container_name: mlflow
    expose: 
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    environment:
      MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"
      AWS_ACCESS_KEY_ID: "access"
      AWS_SECRET_ACCESS_KEY: "secret1234"
      AWS_DEFAULT_REGION: "mzg"
    command: mlflow server --backend-store-uri postgresql://postgres:password@postgres:5432/postgres --default-artifact-root s3://mlflow/ --host 0.0.0.0

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    dbdata: