authentication:
  roles:
  - a-team
  - b-team
  type: stupid
  username: michael
environment:
  AWS_ACCESS_KEY_ID: e75a4d86
  AWS_DEFAULT_REGION: mzg
  AWS_SECRET_ACCESS_KEY: 866007e7
  MLFLOW_S3_ENDPOINT_URL: http://localhost:49499
  MLFLOW_TRACKING_URI: http://localhost:49502
  MQ_PROJECT: 09ce1d5a
project:
  id: 09ce1d5a
  name: michaels-project
url: http://localhost:9042